export const dashboard = <i className="fa-solid fa-house"></i>
export const transactions = <i className="fa-solid fa-hand-holding-dollar"></i>
export const categories = <i className="fa-solid fa-layer-group"></i>
export const accounts = <i className="fa-solid fa-user"></i>
export const settings = <i className="fa-solid fa-gear"></i>
export const logout = <i className="fa-solid fa-left-from-bracket"></i>
export const trend = <i className="fa-solid fa-money-bill-trend-up"></i>
export const expenses = <i className="fa-solid fa-money-bill-transfer"></i>
export const money = <i className="fa-sharp fa-solid fa-money-bill-1-wave"></i>
export const freelance = <i className="fa-solid fa-earth-americas"></i>
export const piggy = <i className="fa-solid fa-piggy-bank"></i>
export const yt = <i className="fa-brands fa-youtube"></i>
export const card = <i className="fa-brands fa-youtube"></i>
export const users = <i className="fa-solid fa-users-between-lines"></i>
export const dollar = <i className="fa-solid fa-rupiah-sign"></i>
export const calendar = <i className="fa-solid fa-calendar"></i>
export const comment = <i className="fa-solid fa-comment"></i>
export const plus = <i className="fa-solid fa-plus"></i>
export const trash = <i className="fa-solid fa-trash"></i>
export const signout = <i className="fa-solid fa-right-from-bracket"></i>
export const takeaway = <i className="fa-solid fa-utensils"></i>
export const clothing = <i className="fa-solid fa-shirt"></i>
export const book = <i className="fa-solid fa-book"></i>
export const food = <i className="fa-solid fa-burger"></i>
export const medical = <i className="fa-solid fa-briefcase-medical"></i>
export const tv = <i className="fa-solid fa-bolt"></i>
export const circle = <i className="fa-solid fa-circle-dot"></i> 
export const add = <i className="fa-solid fa-file-circle-plus"></i>
